### ISSUE TITLE
New comment, but only if comment has changed

### ISSUE THREAD

**Issue by darthsteven** [marocchino/sticky-pull-request-comment#1023]
Thanks so much for this action, it's great!

I'm using it to add comments to PRs of the output of [composer lock diff](https://github.com/davidrjonas/composer-lock-diff), so that we can see the actual changes made to the dependencies.

Basically, that tool produces some output, and it's super handy to have the 'latest' output on the PR.

I've done that with the following in my workflow:

```yaml
      - uses: marocchino/sticky-pull-request-comment@f61b6cf21ef2fcc468f4345cdfcc9bda741d2343
        # We delete empty comments in the action below
        if: ${{ steps.composer_diff.outputs.composer_diff_exit_code != 0 }}
        with:
          header: composer-diff # Identifies our comment
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            ### Results of `composer diff`

            ${{ steps.composer_diff.outputs.composer_diff }}

      - uses: marocchino/sticky-pull-request-comment@f61b6cf21ef2fcc468f4345cdfcc9bda741d2343
        # Remove an empty comment, if there is one.
        if: ${{ steps.composer_diff.outputs.composer_diff_exit_code == 0 }}
        with:
          header: composer-diff # Identifies our comment
          hide: true
          hide_classify: "OUTDATED"
```

This works quite well, you push some commits, and you get the message added.

But then if you push some more commits, then you _can_ get the same contents of the comment posted, but to an entirely new comment.

The other way I've run this workflow is to continually update a comment, but then you've having to go back up the PR and check it, and it might have changed drastically, but you don't notice it etc.!

What I'd like is the option to only post a new comment if the actual comment _body_ has changed. Would that at all be possible with this action?
