### ISSUE TITLE
Warning on hiding already hidden comment

### ISSUE THREAD

**Issue by richja** [marocchino/sticky-pull-request-comment#1082]
Similar to #559, when using `hide: true` and comment is already hidden, I am getting a warning: *Comment body cannot be blank*

```
Run marocchino/sticky-pull-request-comment@v2
  with:
    hide: true
    hide_classify: RESOLVED
    header: ***
    append: false
    recreate: false
    delete: false
    only_create: false
    only_update: false
    hide_details: false
    hide_and_recreate: false
    ignore_empty: false
    skip_unchanged: false
    follow_symbolic_links: false
    GITHUB_TOKEN: ***
  env:
    URL: https://api.github.com/repos/***/issues/564/comments
Warning: Comment body cannot be blank
```

Warning doesn't show up when a comment is not hidden yet.

**Comment by fregante** [comment]
In my case, the comment isn't hidden, I get the warning, and it doesn't get hidden. It seems that `hide: true` as documented in the readme is broken:

https://github.com/marocchino/sticky-pull-request-comment/tree/v2/?tab=readme-ov-file#hide-previous-comment

I'm using 

```yml

      - if: steps.stats.outputs.changes <= 1000
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: lockfile # Unique identifier for the comment
          hide: true
      - if: steps.stats.outputs.changes > 1000
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: lockfile # Unique identifier for the comment
          recreate: true
          message: |
            ## ⚠️ Large diff for package-lock.json
```

Live example https://togithub.com/pixiebrix/pixiebrix-extension/pull/7734#issuecomment-1968463512
Log (for the next 30 days) https://github.com/pixiebrix/pixiebrix-extension/actions/runs/8077604169/job/22068226398?pr=7734
