### ISSUE TITLE
future versions - tagging standards

### ISSUE THREAD

**Issue by troyxmccall** [marocchino/sticky-pull-request-comment#1244]
hi @marocchino 

first of all, thank you for this plugin, I use it in my daily PR workflow

would you consider bumping your major version with the new Node release for future GitHub Action Releases?

aka: https://github.com/actions/checkout/releases released a new major version (v4) for Node20 support

When you bumped https://github.com/marocchino/sticky-pull-request-comment/releases/tag/v2.9.0

to Node v20, those of us on self-hosted runners running `marocchino/sticky-pull-request-comment@v2`

 that don't support Node20 (https://github.com/actions/runner/issues/2906)  experienced a breaking change
 
 of course, the workaround for this breaking change would be for users to move their workflow to a secondary job that runs on a runner that supports Nodev20:
 
 ```
   post-release-details:
    runs-on: ubuntu-latest # Nodev20 support needed for these steps
    needs: checkout-and-build-site
    if: github.actor!= 'dependabot-preview[bot]'   # ignore the pull request which comes from user depbot.
    steps:
      # get vars to pass on later
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${CI_ACTION_REF_NAME_SLUG})" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: post comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Release ${{ github.sha }} has been built on <https://${{ steps.extract_branch.outputs.branch }}.example.dev>
```

but it'd be great for future major releases to stick to their (assigned) node versions for unique runtimes 

Thanks!
