### ISSUE TITLE
IssueComment Body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by xakraz** [marocchino/sticky-pull-request-comment#1395]
We are using your GitHub action to implement a similar UX that Atlantis does for Terraform 😇 

But we face in issue with this error

```
Error: Validation Failed: {"resource":"IssueComment","code":"unprocessable","field":"data","message":"Body is too long (maximum is 65536 characters)"}
```

💡 It would be nice to be able to split the comment in multiple ones if the body is too long.
Atlantis does that for very long Terraform plans output

**Comment by marocchino** [comment]
Finding a proper delimiter for strings exceeding 65536 seems a bit tricky. Please give me some time to think about it. If you have any good ideas, PRs are welcome.

**Comment by marocchino** [comment]
Personally, I don't think anyone would be able to read such a long comment, so it seems better to handle it as an artifact.

**Comment by ShankyJS** [comment]
Ups, I created a duplicate issue for this https://github.com/marocchino/sticky-pull-request-comment/issues/1408.

I just encountered the same issue; It would be really nice to implement a feature similar to atlantis where the comments get chunked into multiple pieces if it's greater than the max size.

Definitely a +1 on this one.

**Comment by dudicoco** [comment]
@marocchino how about adding an input to the action - `delimiter`, the action can than determine if the body is too long and split the comment according to the delimiter.

Example:
```yaml
    - name: Comment on PR
      uses: marocchino/sticky-pull-request-comment@v2.9.0
      with:
        number: ${{ github.event.pull_request.number }}
        delimiter: ---
        message: |
            first comment
            ---
            second comment
            ---
            third comment
```
