### ISSUE TITLE
[ERROR] Post comment to a PR from txt file -> "Either message or path input is required"

### ISSUE THREAD

**Issue by ErickGiffoni** [marocchino/sticky-pull-request-comment#1423]
Github action is this trivy.yml:
```
name: trivy
on:
  pull_request:
    branches: [ "main", "dev", "erick/dev", "niko/dev", "frclba/dev" ]

permissions:
  pull-requests: write
  contents: read


jobs:
  verify:
    name: verify code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'  # Change format to 'table' for readable output in PR comment
          output: 'trivy-results.txt'
          severity: 'CRITICAL'

      - name: Check if Trivy results exist
        run: test -f trivy-results.txt

      - name: Post Trivy scan results as a PR comment
        if: success() || failure() # Ensure this runs even if Trivy fails
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-results.txt
```

**ERROR**
```
> Post Trivy scan results as a PR comment
Run marocchino/sticky-pull-request-comment@v2
  with:
    path: trivy-results.txt
    append: false
    recreate: false
    delete: false
    only_create: false
    only_update: false
    hide_details: false
    hide: false
    hide_and_recreate: false
    hide_classify: OUTDATED
    ignore_empty: false
    skip_unchanged: false
    follow_symbolic_links: false
    GITHUB_TOKEN: ***
Error: Either message or path input is required
```

Can you help ? A couple of days ago I wasn't getting this
