### ISSUE TITLE
keep running into "no numbers given: skip step"

### ISSUE THREAD

**Issue by soerenmartius** [marocchino/sticky-pull-request-comment#233]
Hi and thanks for this repository,

I am trying to get this action working with my pipeline, but keep running into `no numbers given: skip step`. Any advice on what's going on here? 

Thanks a lot!

```
name: CI/CD Pipeline

on: [push]

env:
.....
jobs:
....
  delivery:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform Init & Plan
        id: init-plan 
        run: |
          make terraform/init
          make terraform/plan
      - name: Terraform Output to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            terraform plan output of commit ${{ github.sha }}:
            ```
            ${{ steps.init-and-plan.result }}
            ```
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: make terraform/apply
```

**Comment by marocchino** [comment]
You need set `pr number` to be commended when using push strategies.

- https://github.com/marocchino/sticky-pull-request-comment#comment-from-push
- https://github.com/marocchino/sticky-pull-request-comment/blob/main/action.yml#L20-L22

**Comment by soerenmartius** [comment]
Thanks, that's helpful :)

**Comment by mkubdev** [comment]
Hey, i'm facing this issue.

@soerenmartius did you manage to fix it?

What i did:

* number: ${{ github.event.pull_request.number }} not working
* number: ${{ github.event.number }} not working
* no number (number commented) not working

My context :

```yaml
on:  
  push:
  pull_request:
    branches:
      - master
```

I don't know how to find a way to make this script working. Someone can help?
