### ISSUE TITLE
Leaving two autodelete comments with a path

### ISSUE THREAD

**Issue by mifriis** [marocchino/sticky-pull-request-comment#333]
Hi codeowners,
What an awesome action! We are using it to automate test report output and it works great!

Today i was working on integrating code coverage into it aswell, and I hit a snag that i am hoping you can help with.

I would like to post both the output from testsummary.txt and testcoverage.txt into either 1 or 2 comments on the PR, and have them autodelete.

I am trying this way now:
```YAML
    - name: comment PR with test report
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: Test Report
        path: ${{env.file_name}}
        delete: true

          # add report as PR comment (if PR)
    - name: comment PR with coverage report
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: Coverage Report
        path: ${{github.workspace}}/report/Summary.txt
        delete: true
```

And it works fine when i remove the "delete:true" part. But it kinda fills up the conversation log.

Is it possible to combine path and message to combine them into one comment? Or perhaps 2 comments that each autodeletes itself?

Hope you can help. Thank you.

**Comment by marocchino** [comment]
Two thing.

1. Use `recreate` instead of `delete`. If you want delete previous comment and write comment, delete only **delete** previous one.
2. You can combine two comment with `append`.

```yaml
    - name: comment PR with test report
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: Report
        path: ${{env.file_name}}
        recreate: true

    - name: comment PR with coverage report
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: Report
        path: ${{github.workspace}}/report/Summary.txt
        append: true
```

or prepare comment text as [output](https://trstringer.com/github-actions-multiline-strings/)

```yaml
    - name: create string
      run: |
        OUTPUT=$(cat << EOF
        $(cat ${{env.file_name}})
        $(cat ${{github.workspace}}/report/Summary.txt)
        EOF
        )
        OUTPUT="${OUTPUT//'%'/'%25'}"
        OUTPUT="${OUTPUT//$'\n'/'%0A'}"
        OUTPUT="${OUTPUT//$'\r'/'%0D'}"
        echo "::set-output name=report::$OUTPUT"
      id: report
    - name: comment PR with coverage report
      uses: marocchino/sticky-pull-request-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: Coverage Report
        recreate: true
        message: ${{ steps.report.outputs.report }}
```
