### ISSUE TITLE
Hide option for handling previous comments

### ISSUE THREAD

**Issue by tizmagik** [marocchino/sticky-pull-request-comment#428]
I'd be useful to have the ability to "hide" previous comments instead of deleting them or updating them. Would that be feasible? Would you be open to a PR to add that? If you could point me in the right direction I'd be happy to take a look at adding that feature.

**Comment by marocchino** [comment]
how about

```yaml
append: true
summary: 'some title'
fold: true
content: ---
  content


```

and we can modify last opened details to just  `<details>`
```html 
<details open>
<summary>title</summary>

content
</details>
```

**Comment by marocchino** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#creating_an_open_disclosure_box

**Comment by marocchino** [comment]
or just close previous summary option? 🤔 

```yaml
append: true
summary: 'some title'
hide_summaries: true
content: |
   <details open>
   <summary>title</summary>

   content
   </details>
```
