### ISSUE TITLE
message from an text file

### ISSUE THREAD

**Issue by marocchino** [marocchino/sticky-pull-request-comment#53]
```yaml
    - uses: marocchino/sticky-pull-request-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        path: message.txt
```
