### ISSUE TITLE
delete previous comment tries to create a comment if it cannot find previous comment

### ISSUE THREAD

**Issue by fddayan** [marocchino/sticky-pull-request-comment#559]
if I set `delete: true`, it will try to locate a comment based on the specify header (if any). In the example below is `my-header` and it will try create a comment. It's going to fail because `message` attribute is null, but it's going to print a `warning` message in the workflow. 

```
uses: marocchino/sticky-pull-request-comment@v2.2.0
with:
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  header: my-header
  delete: true
```

warning message in workflow. My job is named `test`

![image](https://user-images.githubusercontent.com/188936/152277693-2872f854-21f2-4cd9-996c-8e1e748e84e6.png)
