### ISSUE TITLE
Cannot hide an existing comment and update its message

### ISSUE THREAD

**Issue by davereid-pfg** [marocchino/sticky-pull-request-comment#561]
I have a use case where I want to hide an existing message and *also* change the message to something like "The preview environment is currently being deployed.". I tried to use this configuration:

```yml
      - name: Hide and update PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ github.job }}
          hide: true
          message: |
            The preview environment is currently being deployed.
```

However this results in two different actions happening: hiding the existing comment, and creating a new comment with the message. Could/should this be supported?

**Comment by marocchino** [comment]
I did not expect this kind of multi use.
since It is hard to expect which action goes first.
I you want replace content goes before of hide.
just separate action will be simplest solution for now.
(internally they are seperated action. hide use minimizeComment, Update use updateComment)
```yaml
      - name: Update PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ github.job }}
          message: |
            The preview environment is currently being deployed.
      - name: Hide PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ github.job }}
          hide: true
```

>> Could this be supported?

Yes. It seems like a general use case, so it seems to be worth implementing. But I want to work after #560 is merged.
