### ISSUE TITLE
Keep running into "no numbers given: skip step"

### ISSUE THREAD

**Issue by mkubdev** [marocchino/sticky-pull-request-comment#634]
Hi, maybe a copycat of #233 but solution seems to doesn't work. Whenever i fire an action, I always get `no numbers given: skip step`

## What i did:

* number: `${{ github.event.pull_request.number }}` not working
* number: `${{ github.event.number }}` not working
* no number (number commented) not working

## My context :

```yaml
on:  
  push:
  pull_request:
    branches:
      - master
```

## Action :

```yaml
- name: Add Lighthouse stats as comment
  id: comment_to_pr
  uses: marocchino/sticky-pull-request-comment@v2.0.0
  with:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    header: lighthouse
    number: ${{ github.event.number }}
    message: ${{ steps.format_lighthouse_score.outputs.comment }}
```

I don't know how to find a way to make this script working. Someone can help?

**Comment by marocchino** [comment]
Maybe, you can try this one for push strategy.

https://github.com/marocchino/sticky-pull-request-comment#comment-from-push

**Comment by marocchino** [comment]
@mkubdev 
In my case. push commit on pr only trigger with pull_request.
but your config can trigger both push and pull_request.
So.. If want to trigger only pull_request, try this one:

```yml
on:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```
