### ISSUE TITLE
Using headers and append in matrix has the chance to lose output

### ISSUE THREAD

**Issue by nwithers-ecr** [marocchino/sticky-pull-request-comment#754]
I am writing a CI pipeline with 10+ microservices. I'd like to make a sticky comment that includes whether each one passed lint and test. Since these operations take considerable time, they are running in a matrix with concurrency. 

At first I tried to do it with outputs and a job after the matrix completed. 

```yaml
name: Test matrix
on:
  workflow_dispatch:

jobs:
  alpha:
    name: "matrix ${{ matrix.dir }}"
    runs-on: ubuntu-20.04
    needs: first
    strategy:
      matrix:
        letter: ["a", "b", "c"]
    outputs:
      letter: ${{ matrix.letter }}
    steps:
      - name: Echo matrix
        run: echo ${{ matrix.letter }}

  comment:
    name: "update"
    runs-on: ubuntu-20.04
    needs: alpha
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          number: 1
          message: |
            ${{ needs.alpha.outputs.letter }}
```

but for whatever reason, a matrix output isn't an array like I had expected, but rather just the value of the job which returns last. So i thought to append inside the matrix jobs. 

```yaml
name: Test matrix
on:
  workflow_dispatch:

jobs:
  first:
    name: "make comment"
    runs-on: ubuntu-20.04
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: release
          recreate: true
          number: 1
          message: |
            # Sticky
  alpha:
    name: "matrix ${{ matrix.dir }}"
    runs-on: ubuntu-20.04
    needs: first
    strategy:
      matrix:
        letter: ["a", "b", "c"]
    outputs:
      letter: ${{ matrix.letter }}
    steps:
      - name: Echo matrix
        run: echo ${{ matrix.letter }}
                
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: release
          append: true
          number: 1
          message: |
            ${{ matrix.letter }}
```

But this turned out to yield results which were missing data. Here's an example run

```
# Sticky
<!-- Sticky Pull Request Commentrelease -->
a
c
```
