### ISSUE TITLE
Only update if it exists 

### ISSUE THREAD

**Issue by fregante** [marocchino/sticky-pull-request-comment#783]
I'm using this excellent action to post a reminder after the first PR approval, but I want to keep the message up to date when the PR content is updated.

Would it be possible to add an `update-only` flag to update the comment only if it already exists? Example:

```yml
name: On edit

on:
  pull_request:
    types:
      - edited

jobs:
  edit:

    runs-on: ubuntu-latest

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          update-only: true # 👈 NEW
          message: PR was updated after approval ⚠️
```

```yml
name: On approval

on:
  pull_request_review:
    types:
      - submitted

jobs:
  approve:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: PR was approved ✅ 
```
