### ISSUE TITLE
Hiding comments doesn't seem to work

### ISSUE THREAD

**Issue by stephledev** [marocchino/sticky-pull-request-comment#825]
I'm trying out a minimal setup where I create a comment and then hide it. However, hiding a previous comment following the procedure described in the [docs](https://github.com/marocchino/sticky-pull-request-comment#hide-previous-comment) doesn't seem to have any effect. 

Given:

```
jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: comment
          message: |
            Initial message

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: comment
          hide: true
          hide_classify: 'OUTDATED'
```
Result:

![image](https://user-images.githubusercontent.com/6168494/202424145-13b95bbe-9b52-406d-a467-f13c5aff606d.png)

To verify that the comment can be found, I added an update step in-between, which seems to work fine, but still leaves me with a visible comment.

Given:
```
jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: comment
          message: |
            Initial message

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: comment
          message: |
            Updated message

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: comment
          hide: true
          hide_classify: 'OUTDATED'
```

Result:

![image](https://user-images.githubusercontent.com/6168494/202424700-ae92b352-bedc-4586-ba2e-3ec2c084a488.png)

Is there anything I'm not doing correctly?
