### ISSUE TITLE
Delete comment does not work

### ISSUE THREAD

**Issue by aslafy-z** [marocchino/sticky-pull-request-comment#829]
I'm trying to delete a comment when the build fails, without success.
Here are the steps:
```yaml
    - name: Add comment with link to preview in the PR
      uses: marocchino/sticky-pull-request-comment@v2.3.0
      if: success()
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: 'deploy-preview'
        message: |
          :rocket: Preview for this PR was successfully deployed at <https://${{ steps.ingress-config.outputs.fqdn }}> :rocket:

    - name: Delete comment with link to preview in the PR
      uses: marocchino/sticky-pull-request-comment@v2.3.0
      if: failure()
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        header: 'deploy-preview'
        delete: true
```

There are no debug logs apart from:
```
##[debug]Loading env
Run marocchino/sticky-pull-request-comment@v2.3.0
  with:
    GITHUB_TOKEN: ***
    header: deploy-preview
    delete: true
    append: false
    recreate: false
    hide_details: false
    hide: false
    hide_and_recreate: false
    hide_classify: OUTDATED
    ignore_empty: true
    follow_symbolic_links: false
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Delete comment with link to preview in the PR
```

Here's the comment content:
```
:rocket: Preview for this PR was successfully deployed at <https://preview-62.[redacted]> :rocket:
<!-- Sticky Pull Request Commentdeploy-preview -->
```

I guess the action does not find the comment. I think it would be nice to add some debug logs.
