### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by ardalis** [marocchino/sticky-pull-request-comment#913]
See this PR: https://github.com/ardalis/GuardClauses/pull/264

I'm getting this result:

> Error: Resource not accessible by integration

Per the README in this repo, the fix for this is to not explicitly use `secrets.GITHUB_TOKEN` but that's not in my build.yml file anywhere.

What else is suggested?

Here's [my build script](https://github.com/ardalis/GuardClauses/blob/main/.github/workflows/build.yml) which has write permissions set:

```yml
name: .NET Core

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
    pull-requests: write 

jobs:
  build:

    runs-on: ubuntu-latest
    


    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '7.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
      # See https://josh-ops.com/posts/github-code-coverage/
      # Add coverlet.collector nuget package to test project - 'dotnet add <TestProject.cspoj> package coverlet
    - name: Test
      run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      
    - name: Copy Coverage To Predictable Location
      run: cp coverage/*/coverage.cobertura.xml coverage/coverage.cobertura.xml
      
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      # uses: joshjohanning/CodeCoverageSummary@v1.0.2
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
```

Thanks!
