### ISSUE TITLE
- Resource not accessible by integration

### ISSUE THREAD

**Issue by daniel-bogart** [marocchino/sticky-pull-request-comment#930]
I've tried omitting the GITHUB_TOKEN, I've tried creating a custom personal access token with every possible permission yet I'm still getting this error: - Resource not accessible by integration

What could possibly be the issue?

```
name: Write deploy comment
on:
  pull_request_target:
    types: [ opened, reopened ]
    branches-ignore:
        - 'production'

jobs:
  trigger:
    name: Write comment with url
    runs-on: ubuntu-latest
    steps:
      - name: Set dev folder
        run: |
          echo "::set-output name=DEV_FOLDER::$(echo ${GITHUB_HEAD_REF} | sed 's|/|-|')"
        id: <organization>

      - name: Write comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: <my token with 100% permissions>
          message: |
            <a href="<my dev build url>">Link live dev site for this PR</a>
```

**Comment by marocchino** [comment]
I've never tried it myself, but I think it probably won't work with pull_request_target. The reason is that it's difficult to meet the condition where the person executing it has access to the PAT (Personal Access Token).
If you want someone without permissions to execute it, I recommend having the output generated in the pull_request and writing the message part in the main branch.

This is my current setting.  

https://github.com/marocchino/sticky-pull-request-comment/blob/main/.github/workflows/
This is my current setup. I think you might need to change `./` to `marocchino/sticky-pull-request-comment@v2`.

**Comment by jgtvares** [comment]
This is happening to me in a repository created by me (in an organization also created by me).

This is the workflow:
```yml
name: PR Checker
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Run tests and report coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: report-markdown
          test-script: npm run test:coverage
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
```

Help!
