### ISSUE TITLE
Delete hidden comments

### ISSUE THREAD

**Issue by MaxymVlasov** [marocchino/sticky-pull-request-comment#990]
### Use case

We currently use your awesome action to automate our CI runs via the `recreate: true` option on each new commit in PR. [Full code](https://github.com/cloudposse/github-action-atmos-affected-trigger-spacelift/blob/96ef24c4d57c75d910d304322d6e9affbdd5b281/action.yml#L133-L141)

But the problem is that comments for CI can be very long, so we'd like to hide them right after creation by adding a second GHA, which hides the current comment:

```yaml
    - name: Create PR Comment with Affected Stacks
      with:
        recreate: true

    - name: Hide comment
      with:
        hide: true
        hide_classify: "RESOLVED"
```

[Full code](https://github.com/MaxymVlasov/github-action-atmos-affected-trigger-spacelift/blob/5c50cc582fa61e283ebbb10b37db1cc4e2c47733/action.yml#L133-L151)

Also, we can't reuse the previous comments, because[ our CI can trigger only on new PR comments](https://docs.spacelift.io/concepts/run/pull-request-comments#pull-request-comment-driven-actions)

### Problem

The problem here is that `recreate` (and `delete`) ignores hidden comments.
I found that ignorance done via https://github.com/marocchino/sticky-pull-request-comment/blob/d7bc2df2c6a0f3d81071342c1ca44b690ce009f2/src/comment.ts#L60 in `findPreviousComment` function

I tried to remove it for test reasons [here](https://github.com/MaxymVlasov/sticky-pull-request-comment/commit/859b055c1533159ea8fbf37766667499852a6a58), but, for some reason it not works.

### Summary

We'd like to have the next comment workflow:
1. Comment N-1 deleted (_which can be hidden_)
2. Comment N created
3. Comment N hidden
4. Repeat for every new commit in PR

But here are some problems with hidden commit removal. How make `sticky-pull-request-comment` able to remove hidden comments?

**Comment by marocchino** [comment]
First of all, Sorry for mess. I don't expect hide and delete will use same time.
In this case `hide_details` will be better than hide.
hide_details just remove open from `<details>` tag.
So It could be deleted.
```yaml
    - name: Create PR Comment with Affected Stacks
      uses: MaxymVlasov/sticky-pull-request-comment@859b055c1533159ea8fbf37766667499852a6a58
      if: ${{ steps.affected-stacks.outputs.has-affected-stacks == 'true' && inputs.trigger-method == 'comment' }}
      with:
        header: atmos-affected-stacks
        recreate: true
        message: |
          <details open>
          <summary>your title</summary>

          ```
          ${{ steps.create-pr-comment-body.outputs.body }}
          ```
          </details>
      env:
        GITHUB_TOKEN: ${{inputs.github-token}}

    - name: Hide comment
      uses: MaxymVlasov/sticky-pull-request-comment@859b055c1533159ea8fbf37766667499852a6a58
      if: ${{ steps.affected-stacks.outputs.has-affected-stacks == 'true' && inputs.trigger-method == 'comment' }}
      with:
        header: atmos-affected-stacks
        hide_details: true
      env:
        GITHUB_TOKEN: ${{inputs.github-token}}
```
